/**
 * The committed baseline, and the rules that hold whatever it says.
 *
 * ## Why both, and not either alone
 *
 * A committed artifact on its own is a snapshot: it catches drift and teaches
 * nothing, and it goes stale the day somebody regenerates it to make a build
 * green. Rules on their own catch no drift — they cannot notice a control that
 * quietly stopped being rendered. Together the artifact says what the surface
 * IS and the rules say what is true of any surface, so a regeneration that
 * breaks a rule still fails.
 *
 * ## Over a MOUNTED surface
 *
 * `renderWorkspace`'s markup is only part of the answer: `mountWorkspace`
 * builds the kind chooser, the target search and its match list as DOM, so a
 * baseline over rendered markup alone would omit the controls whose keyboard
 * behaviour matters most. Mounting is what `mount.test.ts` already does, and it
 * is cheap.
 *
 * ## Regenerating it is deliberately manual
 *
 * The failure prints the exact JSON to paste. There is no `UPDATE=1` flag: a
 * one-keystroke regeneration is how a baseline stops being evidence, and a
 * reviewer seeing a regenerated artifact in a diff should be able to assume a
 * person looked at it. This surface has several leaves open against it, so the
 * artifact WILL be regenerated by other work — the rules below are the part
 * that survives that, and they are what a reviewer should read a regeneration
 * against.
 */

import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { describe, it } from 'node:test';

import { JSDOM } from 'jsdom';

import { a11ySurface } from '../testing/a11y.ts';
import { type ControlEntry, controlSurface } from './baseline.ts';

const BASELINE_PATH = new URL('./baseline.json', import.meta.url);

/**
 * The baseline's three surfaces.
 *
 * THE DISCLOSURE TWICE, because the attributes #149 asks the baseline to cover
 * do not both exist in either state alone: shut, `aria-controls` is correctly
 * absent — the region it would name is not rendered — and open it is present
 * and must resolve. A single-state baseline would cover half of what it claims.
 *
 * AND THE DRAFT IN BOTH ITS STEPS, because the kind chooser and the target
 * search are built by the mount rather than by a renderer, and they are the
 * reason this record is taken over a mounted surface at all. They are two
 * states, not one: `add` renders the chooser, and the search appears only once
 * a kind is chosen — so stopping at the chooser left `target-query`, the match
 * buttons and their cancel out of every surface while this file claimed to
 * cover them. Without these the artifact would be one a spec walk could have
 * produced.
 *
 * AND THE FIRST-PASS QUEUE, because its y/n/s answers are the only controls on
 * the `data-ig-answer` channel. `CONTROL_ATTRIBUTES` names three channels and
 * the rules below quantify over all of them — with the queue closed, one of the
 * three had no members in any surface, so a regression in an answer's
 * accessible name or keyboard reachability passed every rule here.
 */
async function surfaces(): Promise<Record<string, readonly ControlEntry[]>> {
  const out: Record<string, readonly ControlEntry[]> = {};
  for (const [name, options] of [
    ['disclosure-shut', {}],
    ['disclosure-open', { openDiff: true }],
    ['draft-open', { openDraft: true }],
    ['search-open', { openSearch: true }],
    ['first-pass-open', { openFirstPass: true }],
    ['refusal-tier', { refusalTier: true }],
    ['edge-selected', { selectEdge: true }],
    ['isolated-shut', { isolated: true }],
    ['isolated-open', { isolated: true, openIsolated: true }],
    ['held-slot', { held: true }],
  ] as const) {
    const page = await a11ySurface(options);
    try {
      out[name] = controlSurface(page.root);
    } finally {
      page.close();
    }
  }
  return out;
}

/** Every entry across every surface, for a rule that holds of all of them. */
async function everyEntry(): Promise<readonly ControlEntry[]> {
  return Object.values(await surfaces()).flat();
}

describe('the control surface matches its committed baseline', () => {
  it('records the same controls, roles, tab stops, names and ARIA states', async () => {
    {
      const actual = await surfaces();
      const committed: Record<string, readonly ControlEntry[]> = JSON.parse(
        readFileSync(BASELINE_PATH, 'utf8'),
      );
      assert.deepEqual(
        actual,
        committed,
        `the control surface changed. If the change is intended, read it, then paste this into baseline.json:\n${JSON.stringify(actual, null, 2)}\n`,
      );
    }
  });

  // A DENOMINATOR, so a surface that rendered nothing cannot pass every rule
  // below vacuously — the same pin `render.test.ts` puts on its command sweep.
  it('draws a surface worth checking, in both of the disclosure\'s states', async () => {
    const drawn = await surfaces();
    for (const [name, entries] of Object.entries(drawn)) {
      assert.ok(entries.length >= 5, `${name} drew only ${String(entries.length)} controls`);
    }
    // THE ATTRIBUTES THIS BASELINE EXISTS FOR, each in the state that has it.
    const shut = drawn['disclosure-shut']?.find((entry) => entry.control === 'view-diff');
    const open = drawn['disclosure-open']?.find((entry) => entry.control === 'view-diff');
    assert.equal(shut?.aria['aria-expanded'], 'false');
    assert.equal(shut?.aria['aria-controls'], undefined, 'a shut disclosure named a region');
    assert.equal(open?.aria['aria-expanded'], 'true');
    assert.equal(open?.aria['aria-controls'], 'resolves');
  });
});

/**
 * Which controls the recorded states are supposed to contain.
 *
 * DECLARED, NOT SCANNED. Half these names never appear as a literal —
 * `open-isolated` and `close-isolated` come out of a ternary, `target` and
 * `undo` are built at mount — so a grep over the source would report the list
 * it could see and call it complete, which is the failure mode `purity.test.ts`
 * records paying for with a regex it eventually deleted.
 *
 * WHY IT EXISTS AT ALL. Five separate review rounds on this change found the
 * same thing: a control the package renders that no recorded state contained,
 * so a regression in its name, role or tab stop moved neither the artifact nor
 * a rule. Each was a real gap and each was cheap, and there was no end to them,
 * because nothing said which controls the artifact had never seen. This does.
 * Adding a control to the package now fails HERE, on the change that adds it,
 * instead of surfacing one review round at a time on some later pull request.
 */
/** How a control is named in {@link RENDERED_CONTROLS}: its channel and its value. */
function nameOf(entry: ControlEntry): string {
  return `${entry.channel}:${entry.control}`;
}

/**
 * Which controls the recorded states are supposed to contain.
 *
 * QUALIFIED BY CHANNEL, and that is not decoration. Keyed on the control VALUE
 * alone, this list silently exempted a whole channel: `renderAuditHeader`
 * publishes its toggle as a bare boolean `data-ig-audit-filter`, so its value
 * is the empty string — a name no list of command words would ever contain.
 * Deleting the toggle left `missing` empty and every universal rule simply ran
 * over the controls that remained. A coverage check that cannot notice a
 * missing channel is not one.
 *
 * DECLARED, NOT SCANNED. Half these names never appear as a literal —
 * `open-isolated` and `close-isolated` come out of a ternary, `target` and
 * `undo` are built at mount — so a grep over the source would report the list
 * it could see and call it complete, which is the failure `purity.test.ts`
 * records paying for with a regex it eventually deleted. The cost of declaring
 * is that the list can be short by one, and it has been: `refresh` was missing
 * until a review round found it. That is a smaller and more visible failure
 * than the one it replaces.
 *
 * WHY IT EXISTS AT ALL. Five separate review rounds on this change found the
 * same thing: a control the package renders that no recorded state contained,
 * so a regression in its name, role or tab stop moved neither the artifact nor
 * a rule. Adding a control now fails HERE, on the change that adds it.
 *
 * ## What it deliberately does NOT cover
 *
 * THE VIEWER'S OWN CONTROLS. `retry:index`, `review-pick-order` and
 * `dismiss:adoption` are drawn by `@issuegraph/viewer` from host facts this
 * workspace merely forwards, and they are pinned where they are rendered —
 * `viewer/src/states.test.ts` asserts each of them, and asserts that none is
 * drawn when nothing is wired to it. Listing them here would make this file
 * layer 1's second opinion about layer 1's markup, which is the drifting
 * duplicate the package split exists to prevent.
 *
 * That leaves a real gap, and it is a gap in the VIEWER rather than a hole in
 * this list: those controls have their presence pinned and their accessible
 * name, role and tab stop pinned nowhere, because layer 1 has no baseline of
 * its own. Filed rather than absorbed — a baseline for the viewer is its own
 * piece of work with its own fixtures, not three names appended here.
 */
const RENDERED_CONTROLS: readonly string[] = Object.freeze([
  'data-ig-answer:apply',
  'data-ig-answer:reject',
  'data-ig-answer:skip',
  // THE BARE BOOLEAN, spelled out so it cannot be mistaken for a typo and
  // tidied away: the audit toggle's channel carries no value at all.
  'data-ig-audit-filter:',
  'data-ig-command:add',
  'data-ig-command:cancel',
  'data-ig-command:clear',
  'data-ig-command:clear-focus',
  'data-ig-command:close-isolated',
  'data-ig-command:delete',
  'data-ig-command:discard',
  'data-ig-command:first-pass',
  'data-ig-command:first-pass-close',
  'data-ig-command:flip',
  'data-ig-command:focus',
  'data-ig-command:kind',
  'data-ig-command:open-isolated',
  'data-ig-command:refresh',
  'data-ig-command:retry',
  'data-ig-command:retype',
  'data-ig-command:search',
  'data-ig-command:select-edge',
  'data-ig-command:select-issue',
  'data-ig-command:target',
  'data-ig-command:target-query',
  'data-ig-command:undo',
  'data-ig-command:view-diff',
]);

/**
 * Controls the fixture cannot reach, each with the reason.
 *
 * A NAMED GAP IS NOT THE SAME AS AN UNKNOWN ONE. An entry here is a decision
 * someone made and wrote down; a control missing from both lists is an
 * oversight the test now refuses.
 */
const UNREACHABLE: Readonly<Record<string, string>> = Object.freeze({
  // The re-evaluate summary is drawn from a LANDED edit that moved the order,
  // and every write this fixture stages is refused or conflicted on purpose —
  // the recovery cards are what it exists to record. A landed-and-moved state
  // is a different fixture, not another step in this one.
  'data-ig-command:dismiss-change': 'needs a landed edit that moved the order',
});

describe('the recorded states cover what the package renders', () => {
  it('records every control, or names why it cannot', async () => {
    const seen = new Set((await everyEntry()).map(nameOf));
    const missing = RENDERED_CONTROLS.filter(
      (control) => !seen.has(control) && UNREACHABLE[control] === undefined,
    );
    assert.deepEqual(
      missing,
      [],
      `no recorded state contains: ${missing.join(', ')} — add a surface that draws them, or name them in UNREACHABLE with a reason`,
    );
  });

  it('does not carry a reason for a control it actually records', async () => {
    // AN EXEMPTION THAT STOPPED BEING TRUE IS A LIE THE NEXT READER INHERITS.
    const seen = new Set((await everyEntry()).map(nameOf));
    for (const control of Object.keys(UNREACHABLE)) {
      assert.equal(seen.has(control), false, `${control} is recorded — drop its UNREACHABLE entry`);
    }
  });
});

describe('rules that hold whatever the baseline says', () => {
  const each = async (check: (entry: ControlEntry) => void): Promise<void> => {
    for (const entry of await everyEntry()) check(entry);
  };

  it('puts every control somewhere the keyboard can reach', async () => {
    // WIDER THAN `render.test.ts`'s SWEEP, which asserts the carrier is a
    // `button` over `renderWorkspace`'s markup. This runs over the MOUNTED
    // surface, so it also covers the chooser and the target search that never
    // pass a renderer — and it reads the tab order rather than the tag, so a
    // `tabindex="-1"` control does not pass as reachable.
    // EXCEPT WHERE IT IS DELIBERATE. A control under an `inert` subtree is out
    // of the tab order on purpose — the mount makes the zones inert while the
    // first-pass overlay is up — and demanding reachability there would fail on
    // the modal behaving correctly. The exemption is narrow and it is a fact
    // read off the markup, not a list of names anyone can add to.
    // `tab`, NOT "ANYTHING BUT none". Rejecting only `none` accepted
    // `programmatic` — a control at `tabindex="-1"`, reachable by pointer and
    // by a script and by no key — which is the precise defect `TabStop`'s own
    // header says the three-valued field exists to catch. So the rule
    // contradicted the reason the field is not a boolean, and a tab stop
    // regressing to -1 would have regenerated the artifact and passed.
    await each((entry) => {
      if (entry.inert) return;
      assert.equal(
        entry.tabStop,
        'tab',
        `${entry.channel}="${entry.control}" in ${entry.zone ?? 'no zone'} is not in the tab order (${entry.tabStop})`,
      );
    });
  });

  it('gives every control an accessible name', async () => {
    // BOTH FAILURES, because they are different mistakes with the same effect.
    // `none` is a control nobody labelled; `empty` is an `aria-label=""` — an
    // author who meant to name it and named nothing, which reads as deliberate
    // in the markup and is why it earns its own answer rather than folding into
    // `none`.
    await each((entry) => {
      assert.ok(
        entry.name !== 'none' && entry.name !== 'empty',
        `${entry.channel}="${entry.control}" in ${entry.zone ?? 'no zone'} has no accessible name (${entry.name})`,
      );
    });
  });

  it('never leaves an ARIA value empty', async () => {
    // ITS SUBJECT IS THE ENUMERATED STATES, and saying so is the point: an
    // earlier revision cited `aria-label=""` here, which `entry.aria` does not
    // carry — so the rule had no input that could fail it and passed
    // vacuously. The empty-label case is real and is caught one rule up, by
    // `NameSource`'s own `empty`. What is left for this rule is a state
    // attribute rendered with no value, which `renderMarkup` will emit
    // because it omits only `undefined`, `null` and `false`.
    await each((entry) => {
      for (const [attribute, value] of Object.entries(entry.aria)) {
        assert.notEqual(value, '', `${entry.control} carries an empty ${attribute}`);
      }
    });
  });

  it('never hides a control the keyboard can still land on', async () => {
    await each((entry) => {
      if (entry.aria['aria-hidden'] !== 'true') return;
      assert.equal(
        entry.tabStop,
        'none',
        `${entry.control} is aria-hidden but still in the tab order — a stop that announces nothing`,
      );
    });
  });

  it('never leaves an ARIA reference dangling', async () => {
    // `aria-controls` on the disclosure names the region it opens. A dangling
    // id is invisible on screen and total for a screen-reader user, and the id
    // is generated per mutation — so what is recorded, and checked, is that it
    // RESOLVES rather than what it says.
    await each((entry) => {
      for (const [attribute, value] of Object.entries(entry.aria)) {
        if (!attribute.startsWith('aria-')) continue;
        assert.notEqual(value, 'dangling', `${entry.control}'s ${attribute} names nothing`);
      }
    });
  });
});


/**
 * The reader itself, on markup this package does not render.
 *
 * KEPT AFTER THE EXPORT WAS WITHDRAWN, and worth saying why. These cases are no
 * longer a published contract, but they are cheap, they are already correct,
 * and each one pins a rule in this file against a shape that would make it pass
 * silently — an `aria-hidden` wrapper, an `aria-labelledby` naming nothing, a
 * `hidden` subtree. Deleting them would remove evidence, not obligation.
 */
describe('controlSurface reads markup this package does not itself render', () => {
  const read = (body: string): readonly ControlEntry[] => {
    const dom = new JSDOM(`<!doctype html><html><body>${body}</body></html>`);
    try {
      const root = dom.window.document.body;
      return controlSurface(root);
    } finally {
      dom.window.close();
    }
  };

  const only = (body: string): ControlEntry => {
    const entries = read(body);
    assert.equal(entries.length, 1, `expected one control, got ${String(entries.length)}`);
    const entry = entries[0];
    assert.ok(entry !== undefined);
    return entry;
  };

  it('takes a control inside a hidden subtree out of the tab order', () => {
    assert.equal(
      only('<div hidden><button data-ig-command="x">Go</button></div>').tabStop,
      'none',
    );
    // The control on its own is a tab stop, so the assertion above is about
    // `hidden` rather than about buttons.
    assert.equal(only('<button data-ig-command="x">Go</button>').tabStop, 'tab');
  });

  it('does not count a disabled control as reachable', () => {
    assert.equal(only('<button data-ig-command="x" disabled>Go</button>').tabStop, 'none');
  });

  it('reads a name from a wrapping label and from one that names it', () => {
    assert.equal(
      only('<label>Find an issue<input data-ig-command="q"></label>').name,
      'label',
    );
    assert.equal(
      only('<label for="q">Find an issue</label><input id="q" data-ig-command="q">').name,
      'label',
    );
  });

  it('calls an aria-labelledby that names no text empty, not a name', () => {
    // THE POINT OF THE `empty` ANSWER. The reference resolves — the element is
    // there — and the computed accessible name is still nothing, so reading the
    // attribute alone would report a named control that announces silence.
    assert.equal(
      only('<span id="n"></span><button data-ig-command="x" aria-labelledby="n"></button>').name,
      'empty',
    );
    assert.equal(
      only('<span id="n">Retry</span><button data-ig-command="x" aria-labelledby="n"></button>').name,
      'aria-labelledby',
    );
  });

  it('does not accept an empty aria-label as a name', () => {
    assert.equal(only('<button data-ig-command="x" aria-label="">Go</button>').name, 'empty');
    // NOR ONE MADE OF SPACES, which a template padding an empty translation
    // produces and which the browser exposes as no name at all.
    assert.equal(only('<button data-ig-command="x" aria-label="  ">Go</button>').name, 'empty');
  });

  it('ignores text that only a screen reader cannot see', () => {
    assert.equal(
      only('<button data-ig-command="x"><span aria-hidden="true">✕</span></button>').name,
      'none',
    );
    // NATIVELY HIDDEN COUNTS TOO. This subtree is not rendered at all, so the
    // button is exposed with no accessible name — counting its text reported
    // one and let the naming rule pass on a silent control.
    assert.equal(
      only('<button data-ig-command="x"><span hidden>Save</span></button>').name,
      'none',
    );
  });

  it('gives an anchor a role only when it can be followed', () => {
    assert.equal(only('<a data-ig-command="x">Open</a>').role, null);
    assert.equal(only('<a href="#a" data-ig-command="x">Open</a>').role, 'link');
  });

  it('takes an input\'s role from its type', () => {
    assert.equal(only('<input type="search" data-ig-command="q" aria-label="q">').role, 'searchbox');
    assert.equal(only('<input data-ig-command="q" aria-label="q">').role, 'textbox');
    assert.equal(only('<input type="color" data-ig-command="q" aria-label="q">').role, null);
  });

  it('resolves a name the way the browser does when both attributes are set', () => {
    // PRECEDENCE, NOT PREFERENCE. Accessible-name computation takes
    // `aria-labelledby` first, so a control with both is exposed with the empty
    // name its reference resolves to — and reporting the fallback label would
    // pass the naming rule on a control that announces nothing.
    assert.equal(
      only(
        '<span id="n"></span><button data-ig-command="x" aria-label="Retry" aria-labelledby="n"></button>',
      ).name,
      'empty',
    );
  });

  it('inherits aria-hidden from a wrapper, so a hidden tab stop is visible', () => {
    const entry = only('<div aria-hidden="true"><button data-ig-command="x">Go</button></div>');
    assert.equal(entry.aria['aria-hidden'], 'true');
    // AND IT IS STILL A TAB STOP, which is the pairing the rule rejects:
    // `aria-hidden` hides from the accessibility tree and does not remove
    // focus, unlike `hidden` and `inert`.
    assert.equal(entry.tabStop, 'tab');
  });

  it('reports a reference to a missing id as dangling', () => {
    assert.equal(
      only('<button data-ig-command="x" aria-controls="gone">Go</button>').aria['aria-controls'],
      'dangling',
    );
  });

  it('survives an id a selector could not have carried', () => {
    // THE INJECTION THIS MODULE HAD TO REMOVE ONCE. An id is host data, and an
    // earlier revision built `[id="${id}"]` from it — this input made the
    // reader throw rather than answer.
    const entry = only('<button data-ig-command="x" aria-describedby=\'a"]\'>Go</button>');
    assert.equal(entry.aria['aria-describedby'], 'dangling');
  });
});
