/**
 * The committed baseline, and the rules that hold whatever it says.
 *
 * ## Why both, and not either alone
 *
 * A committed artifact on its own is a snapshot: it catches drift and teaches
 * nothing, and it goes stale the day somebody regenerates it to make a build
 * green. Rules on their own catch no drift — they cannot notice a control that
 * quietly stopped being rendered. Together the artifact says what the surface
 * IS and the rules say what is true of any surface, so a regeneration that
 * breaks a rule still fails.
 *
 * ## Over a MOUNTED surface
 *
 * `renderWorkspace`'s markup is only part of the answer: `mountWorkspace`
 * builds the kind chooser, the target search and its match list as DOM, so a
 * baseline over rendered markup alone would omit the controls whose keyboard
 * behaviour matters most. Mounting is what `mount.test.ts` already does, and it
 * is cheap.
 *
 * ## Regenerating it is deliberately manual
 *
 * The failure prints the exact JSON to paste. There is no `UPDATE=1` flag: a
 * one-keystroke regeneration is how a baseline stops being evidence, and a
 * reviewer seeing a regenerated artifact in a diff should be able to assume a
 * person looked at it. This surface has several leaves open against it, so the
 * artifact WILL be regenerated by other work — the rules below are the part
 * that survives that, and they are what a reviewer should read a regeneration
 * against.
 */

import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { describe, it } from 'node:test';

import { a11ySurface } from '../testing/a11y.ts';
import { type ControlEntry, controlSurface } from './baseline.ts';

const BASELINE_PATH = new URL('./baseline.json', import.meta.url);

/**
 * The baseline's three surfaces.
 *
 * THE DISCLOSURE TWICE, because the attributes #149 asks the baseline to cover
 * do not both exist in either state alone: shut, `aria-controls` is correctly
 * absent — the region it would name is not rendered — and open it is present
 * and must resolve. A single-state baseline would cover half of what it claims.
 *
 * AND THE DRAFT OPEN, because the kind chooser and the target search are built
 * by the mount rather than by a renderer, and they are the reason this record
 * is taken over a mounted surface at all. Without them the artifact would be
 * one a spec walk could have produced, and the rules would never meet a
 * `tabindex`.
 */
async function surfaces(): Promise<Record<string, readonly ControlEntry[]>> {
  const out: Record<string, readonly ControlEntry[]> = {};
  for (const [name, options] of [
    ['disclosure-shut', {}],
    ['disclosure-open', { openDiff: true }],
    ['draft-open', { openDraft: true }],
  ] as const) {
    const page = await a11ySurface(options);
    try {
      out[name] = controlSurface(page.root);
    } finally {
      page.close();
    }
  }
  return out;
}

/** Every entry across every surface, for a rule that holds of all of them. */
async function everyEntry(): Promise<readonly ControlEntry[]> {
  return Object.values(await surfaces()).flat();
}

describe('the control surface matches its committed baseline', () => {
  it('records the same controls, roles, tab stops, names and ARIA states', async () => {
    {
      const actual = await surfaces();
      const committed: Record<string, readonly ControlEntry[]> = JSON.parse(
        readFileSync(BASELINE_PATH, 'utf8'),
      );
      assert.deepEqual(
        actual,
        committed,
        `the control surface changed. If the change is intended, read it, then paste this into baseline.json:\n${JSON.stringify(actual, null, 2)}\n`,
      );
    }
  });

  // A DENOMINATOR, so a surface that rendered nothing cannot pass every rule
  // below vacuously — the same pin `render.test.ts` puts on its command sweep.
  it('draws a surface worth checking, in both of the disclosure\'s states', async () => {
    const drawn = await surfaces();
    for (const [name, entries] of Object.entries(drawn)) {
      assert.ok(entries.length >= 5, `${name} drew only ${String(entries.length)} controls`);
    }
    // THE ATTRIBUTES THIS BASELINE EXISTS FOR, each in the state that has it.
    const shut = drawn['disclosure-shut']?.find((entry) => entry.control === 'view-diff');
    const open = drawn['disclosure-open']?.find((entry) => entry.control === 'view-diff');
    assert.equal(shut?.aria['aria-expanded'], 'false');
    assert.equal(shut?.aria['aria-controls'], undefined, 'a shut disclosure named a region');
    assert.equal(open?.aria['aria-expanded'], 'true');
    assert.equal(open?.aria['aria-controls'], 'resolves');
  });
});

describe('rules that hold whatever the baseline says', () => {
  const each = async (check: (entry: ControlEntry) => void): Promise<void> => {
    for (const entry of await everyEntry()) check(entry);
  };

  it('puts every control somewhere the keyboard can reach', async () => {
    // WIDER THAN `render.test.ts`'s SWEEP, which asserts the carrier is a
    // `button` over `renderWorkspace`'s markup. This runs over the MOUNTED
    // surface, so it also covers the chooser and the target search that never
    // pass a renderer — and it reads the tab order rather than the tag, so a
    // `tabindex="-1"` control does not pass as reachable.
    await each((entry) => {
      assert.notEqual(entry.tabStop, 'none', `${entry.control} is not reachable by keyboard`);
    });
  });

  it('gives every control an accessible name', async () => {
    // BOTH FAILURES, because they are different mistakes with the same effect.
    // `none` is a control nobody labelled; `empty` is an `aria-label=""` — an
    // author who meant to name it and named nothing, which reads as deliberate
    // in the markup and is why it earns its own answer rather than folding into
    // `none`.
    await each((entry) => {
      assert.ok(
        entry.name !== 'none' && entry.name !== 'empty',
        `${entry.control} has no accessible name (${entry.name})`,
      );
    });
  });

  it('never leaves an ARIA value empty', async () => {
    // ITS SUBJECT IS THE ENUMERATED STATES, and saying so is the point: an
    // earlier revision cited `aria-label=""` here, which `entry.aria` does not
    // carry — so the rule had no input that could fail it and passed
    // vacuously. The empty-label case is real and is caught one rule up, by
    // `NameSource`'s own `empty`. What is left for this rule is a state
    // attribute rendered with no value, which `renderMarkup` will emit
    // because it omits only `undefined`, `null` and `false`.
    await each((entry) => {
      for (const [attribute, value] of Object.entries(entry.aria)) {
        assert.notEqual(value, '', `${entry.control} carries an empty ${attribute}`);
      }
    });
  });

  it('never hides a control the keyboard can still land on', async () => {
    await each((entry) => {
      if (entry.aria['aria-hidden'] !== 'true') return;
      assert.equal(
        entry.tabStop,
        'none',
        `${entry.control} is aria-hidden but still in the tab order — a stop that announces nothing`,
      );
    });
  });

  it('never leaves an ARIA reference dangling', async () => {
    // `aria-controls` on the disclosure names the region it opens. A dangling
    // id is invisible on screen and total for a screen-reader user, and the id
    // is generated per mutation — so what is recorded, and checked, is that it
    // RESOLVES rather than what it says.
    await each((entry) => {
      for (const [attribute, value] of Object.entries(entry.aria)) {
        if (!attribute.startsWith('aria-')) continue;
        assert.notEqual(value, 'dangling', `${entry.control}'s ${attribute} names nothing`);
      }
    });
  });
});
