/**
 * Write the demo's version stamp from the workspace manifests.
 *
 * The sandbox states which package versions it runs, and the honest source of
 * that is the manifest of each package the page loads — read at BUILD time,
 * because the browser cannot import a sibling package's `package.json` without
 * reaching past the seam the lint config refuses, and a hand-maintained list
 * is a list that is wrong the release after it was written.
 *
 * The output is a TypeScript module the demo imports like any other, generated
 * into `demo/src/versions.ts` by the demo's own `build` script and gitignored:
 * it is build output that happens to be source-shaped. `pnpm run ci` builds
 * before it typechecks, lints or tests, so every consumer of the file sees it.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

/** The packages whose versions the page states, in the order it states them. */
export const STAMPED_PACKAGES = Object.freeze([
  'viewer',
  'editor',
  'store',
  'derive',
  'reader',
  'core',
] as const);

export type StampedPackage = (typeof STAMPED_PACKAGES)[number];

export type Versions = Readonly<Record<StampedPackage, string>>;

interface Manifest {
  readonly name?: unknown;
  readonly version?: unknown;
}

function manifestOf(root: string, name: StampedPackage): Manifest {
  const parsed: unknown = JSON.parse(
    readFileSync(join(root, 'packages', name, 'package.json'), 'utf8'),
  );
  if (typeof parsed !== 'object' || parsed === null) {
    throw new Error(`packages/${name}/package.json is not an object`);
  }
  return parsed;
}

function versionOf(root: string, name: StampedPackage): string {
  const manifest = manifestOf(root, name);
  if (manifest.name !== `@issuegraph/${name}`) {
    throw new Error(`packages/${name}/package.json names ${String(manifest.name)}`);
  }
  if (typeof manifest.version !== 'string' || manifest.version === '') {
    throw new Error(`packages/${name}/package.json has no version`);
  }
  return manifest.version;
}

/**
 * Read each stamped package's version off its manifest.
 *
 * Spelled out per key rather than built from `Object.fromEntries`, so the
 * result is the record type by construction and no assertion is needed.
 */
export function readVersions(root: string): Versions {
  return Object.freeze({
    viewer: versionOf(root, 'viewer'),
    editor: versionOf(root, 'editor'),
    store: versionOf(root, 'store'),
    derive: versionOf(root, 'derive'),
    reader: versionOf(root, 'reader'),
    core: versionOf(root, 'core'),
  });
}

/** The module text: a frozen record, plus the names in stamping order. */
export function renderVersionsModule(versions: Versions): string {
  const lines = STAMPED_PACKAGES.map(
    (name) => `  ${JSON.stringify(name)}: ${JSON.stringify(versions[name])},`,
  );
  return [
    '// GENERATED by scripts/stamp-demo-versions.ts from the workspace manifests.',
    '// Do not edit; run the demo build. Gitignored on purpose: it is build output.',
    '',
    '/** The packages the sandbox runs, in the order the page states them. */',
    `export const STAMPED_PACKAGES = Object.freeze(${JSON.stringify([...STAMPED_PACKAGES])} as const);`,
    '',
    'export type StampedPackage = (typeof STAMPED_PACKAGES)[number];',
    '',
    '/** Each package version, read off its manifest when the demo was built. */',
    'export const VERSIONS: Readonly<Record<StampedPackage, string>> = Object.freeze({',
    ...lines,
    '});',
    '',
  ].join('\n');
}

const invokedDirectly =
  process.argv[1] !== undefined && resolve(process.argv[1]) === fileURLToPath(import.meta.url);

if (invokedDirectly) {
  const root = resolve(fileURLToPath(new URL('..', import.meta.url)));
  const target = join(root, 'demo', 'src', 'versions.ts');
  writeFileSync(target, renderVersionsModule(readVersions(root)));
}
